import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/components/Providers";

const noto = Noto_Sans_KR({
  weight: ["300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr" suppressHydrationWarning>
      <body className={noto.className}>
        <Providers>
          <div className="min-h-dvh w-full">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
